
[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 20.0

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.98
# opacity = 0.5
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 3
y = 5

[general]
import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
  # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml",
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml",
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml",
]


